### ISSUE TITLE
which command coordination inserted on terminal from finshir should to take down, offline, one website, with http/https even with ip clouds. ?

### ISSUE THREAD

**Issue by darknodi** [Hippolot/finshir#11]
@pickfire @Hippolot 

java/rust/c 

the best language on this world.

**Comment by Hippolot** [comment]
Hello. I don't understand the question, but generally you should look at the command-line options in `README.md`.

**Comment by pickfire** [comment]
@darknodi Err, I think that question above is illegal?

> java/rust/c
>
> the best language on this world.

@darknodi Is that a statement? If yes, I may not agree to the java part, I think it is the opposite. But let's take this discussion somewhere else.

**Comment by Hippolot** [comment]
> @darknodi Err, I think that question above is illegal?

If he/she wants to damage someone's else website without asking a permission, then yes, but the given information is incomplete.

> @darknodi Is that a statement? If yes, I may not agree to the java part, I think it is the opposite. But let's take this discussion somewhere else.

Absolutely!

**Comment by darknodi** [comment]
@Hippolot @pickfire 

from one domain statistic address. 

example finshir --receiver domain.com --connections 15000 

I would want to ddosing all statistic address domains with this ranged 

like Postscan & Stuff 

from 1.1.1.1 -244 

finshir --reciever domain.com --connections 1000 -p 22 

tcp/syn ack -icmp flooding

**Comment by Hippolot** [comment]
Closed, because it's a quite strange issue.
